modLoader = "javafml"
loaderVersion = "[28,)"

license = "MIT"
[[mods]]
modId = "ferritecore"
version = "${file.jarVersion}"
displayName = "Ferrite Core"
authors = "malte0811"
description = '''
Reduces memory usage.
'''
logoFile = "logo.png"
[[dependencies.ferritecore]]
modId = "forge"
mandatory = true
versionRange = "[40.0.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ferritecore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
