name: Run tests on Java 8 and Java 16-ea
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    # TODO this should probably be a matrix build, but gradle needs arguments to calm down 16-ea that don't work on 8
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test on Java 8
        run: ./gradlew common:test
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Use gradle 7.0 pre 1 for Java 16 test
        run: sed -i "s/6\.8/7.0-rc-1/" gradle/wrapper/gradle-wrapper.properties
      - name: Test on Java 16
        run: ./gradlew common:test --rerun-tasks
